#pragma once
#include "sdkconfig.h"
#include <cstddef> // for size_t
#include <cstdint>
#include <string>
#define DL_IMAGE_PIX_CVT_ID(src_pix_type, dst_pix_type) (((src_pix_type) << 16) | (dst_pix_type))

namespace dl {
namespace image {

typedef enum {
    DL_IMAGE_PIX_TYPE_RGB888 = 0,
    DL_IMAGE_PIX_TYPE_RGB888_QINT8,
    DL_IMAGE_PIX_TYPE_RGB888_QINT16,
    DL_IMAGE_PIX_TYPE_BGR888,
    DL_IMAGE_PIX_TYPE_BGR888_QINT8,
    DL_IMAGE_PIX_TYPE_BGR888_QINT16,
    DL_IMAGE_PIX_TYPE_GRAY,
    DL_IMAGE_PIX_TYPE_GRAY_QINT8,
    DL_IMAGE_PIX_TYPE_GRAY_QINT16,
    DL_IMAGE_PIX_TYPE_RGB565LE,
    DL_IMAGE_PIX_TYPE_RGB565BE,
    DL_IMAGE_PIX_TYPE_BGR565LE,
    DL_IMAGE_PIX_TYPE_BGR565BE,
    DL_IMAGE_PIX_TYPE_HSV,
    DL_IMAGE_PIX_TYPE_HSV_MASK
} pix_type_t;

inline std::string pix_type2str(pix_type_t pix_type)
{
    switch (pix_type) {
    case DL_IMAGE_PIX_TYPE_RGB888:
        return "DL_IMAGE_PIX_TYPE_RGB888";
    case DL_IMAGE_PIX_TYPE_RGB888_QINT8:
        return "DL_IMAGE_PIX_TYPE_RGB888_QINT8";
    case DL_IMAGE_PIX_TYPE_RGB888_QINT16:
        return "DL_IMAGE_PIX_TYPE_RGB888_QINT16";
    case DL_IMAGE_PIX_TYPE_BGR888:
        return "DL_IMAGE_PIX_TYPE_BGR888";
    case DL_IMAGE_PIX_TYPE_BGR888_QINT8:
        return "DL_IMAGE_PIX_TYPE_BGR888_QINT8";
    case DL_IMAGE_PIX_TYPE_BGR888_QINT16:
        return "DL_IMAGE_PIX_TYPE_BGR888_QINT16";
    case DL_IMAGE_PIX_TYPE_GRAY:
        return "DL_IMAGE_PIX_TYPE_GRAY";
    case DL_IMAGE_PIX_TYPE_GRAY_QINT8:
        return "DL_IMAGE_PIX_TYPE_GRAY_QINT8";
    case DL_IMAGE_PIX_TYPE_GRAY_QINT16:
        return "DL_IMAGE_PIX_TYPE_GRAY_QINT16";
    case DL_IMAGE_PIX_TYPE_RGB565LE:
        return "DL_IMAGE_PIX_TYPE_RGB565LE";
    case DL_IMAGE_PIX_TYPE_RGB565BE:
        return "DL_IMAGE_PIX_TYPE_RGB565BE";
    case DL_IMAGE_PIX_TYPE_BGR565LE:
        return "DL_IMAGE_PIX_TYPE_BGR565LE";
    case DL_IMAGE_PIX_TYPE_BGR565BE:
        return "DL_IMAGE_PIX_TYPE_BGR565BE";
    case DL_IMAGE_PIX_TYPE_HSV:
        return "DL_IMAGE_PIX_TYPE_HSV";
    case DL_IMAGE_PIX_TYPE_HSV_MASK:
        return "DL_IMAGE_PIX_TYPE_HSV_MASK";
    default:
        return "UKN_PIX_TYPE";
    }
}

typedef enum {
    DL_IMAGE_PIX_CVT_RGB8882RGB888 = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB888, DL_IMAGE_PIX_TYPE_RGB888),
    DL_IMAGE_PIX_CVT_RGB8882RGB888_QINT8 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB888, DL_IMAGE_PIX_TYPE_RGB888_QINT8),
    DL_IMAGE_PIX_CVT_RGB8882RGB888_QINT16 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB888, DL_IMAGE_PIX_TYPE_RGB888_QINT16),
    DL_IMAGE_PIX_CVT_RGB8882BGR888 = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB888, DL_IMAGE_PIX_TYPE_BGR888),
    DL_IMAGE_PIX_CVT_RGB8882BGR888_QINT8 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB888, DL_IMAGE_PIX_TYPE_BGR888_QINT8),
    DL_IMAGE_PIX_CVT_RGB8882BGR888_QINT16 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB888, DL_IMAGE_PIX_TYPE_BGR888_QINT16),
    DL_IMAGE_PIX_CVT_RGB8882GRAY = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB888, DL_IMAGE_PIX_TYPE_GRAY),
    DL_IMAGE_PIX_CVT_RGB8882GRAY_QINT8 = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB888, DL_IMAGE_PIX_TYPE_GRAY_QINT8),
    DL_IMAGE_PIX_CVT_RGB8882GRAY_QINT16 = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB888, DL_IMAGE_PIX_TYPE_GRAY_QINT16),
    DL_IMAGE_PIX_CVT_RGB8882RGB565LE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB888, DL_IMAGE_PIX_TYPE_RGB565LE),
    DL_IMAGE_PIX_CVT_RGB8882RGB565BE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB888, DL_IMAGE_PIX_TYPE_RGB565BE),
    DL_IMAGE_PIX_CVT_RGB8882BGR565LE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB888, DL_IMAGE_PIX_TYPE_BGR565LE),
    DL_IMAGE_PIX_CVT_RGB8882BGR565BE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB888, DL_IMAGE_PIX_TYPE_BGR565BE),
    DL_IMAGE_PIX_CVT_RGB8882HSV = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB888, DL_IMAGE_PIX_TYPE_HSV),
    DL_IMAGE_PIX_CVT_RGB8882HSV_MASK = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB888, DL_IMAGE_PIX_TYPE_HSV_MASK),
    DL_IMAGE_PIX_CVT_BGR8882RGB888 = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR888, DL_IMAGE_PIX_TYPE_RGB888),
    DL_IMAGE_PIX_CVT_BGR8882RGB888_QINT8 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR888, DL_IMAGE_PIX_TYPE_RGB888_QINT8),
    DL_IMAGE_PIX_CVT_BGR8882RGB888_QINT16 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR888, DL_IMAGE_PIX_TYPE_RGB888_QINT16),
    DL_IMAGE_PIX_CVT_BGR8882BGR888 = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR888, DL_IMAGE_PIX_TYPE_BGR888),
    DL_IMAGE_PIX_CVT_BGR8882BGR888_QINT8 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR888, DL_IMAGE_PIX_TYPE_BGR888_QINT8),
    DL_IMAGE_PIX_CVT_BGR8882BGR888_QINT16 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR888, DL_IMAGE_PIX_TYPE_BGR888_QINT16),
    DL_IMAGE_PIX_CVT_BGR8882GRAY = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR888, DL_IMAGE_PIX_TYPE_GRAY),
    DL_IMAGE_PIX_CVT_BGR8882GRAY_QINT8 = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR888, DL_IMAGE_PIX_TYPE_GRAY_QINT8),
    DL_IMAGE_PIX_CVT_BGR8882GRAY_QINT16 = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR888, DL_IMAGE_PIX_TYPE_GRAY_QINT16),
    DL_IMAGE_PIX_CVT_BGR8882RGB565LE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR888, DL_IMAGE_PIX_TYPE_RGB565LE),
    DL_IMAGE_PIX_CVT_BGR8882RGB565BE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR888, DL_IMAGE_PIX_TYPE_RGB565BE),
    DL_IMAGE_PIX_CVT_BGR8882BGR565LE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR888, DL_IMAGE_PIX_TYPE_BGR565LE),
    DL_IMAGE_PIX_CVT_BGR8882BGR565BE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR888, DL_IMAGE_PIX_TYPE_BGR565BE),
    DL_IMAGE_PIX_CVT_BGR8882HSV = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR888, DL_IMAGE_PIX_TYPE_HSV),
    DL_IMAGE_PIX_CVT_BGR8882HSV_MASK = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR888, DL_IMAGE_PIX_TYPE_HSV_MASK),
    DL_IMAGE_PIX_CVT_GRAY2GRAY = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_GRAY, DL_IMAGE_PIX_TYPE_GRAY),
    DL_IMAGE_PIX_CVT_GRAY2GRAY_QINT8 = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_GRAY, DL_IMAGE_PIX_TYPE_GRAY_QINT8),
    DL_IMAGE_PIX_CVT_GRAY2GRAY_QINT16 = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_GRAY, DL_IMAGE_PIX_TYPE_GRAY_QINT16),
    DL_IMAGE_PIX_CVT_RGB565LE2RGB888 = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565LE, DL_IMAGE_PIX_TYPE_RGB888),
    DL_IMAGE_PIX_CVT_RGB565LE2RGB888_QINT8 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565LE, DL_IMAGE_PIX_TYPE_RGB888_QINT8),
    DL_IMAGE_PIX_CVT_RGB565LE2RGB888_QINT16 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565LE, DL_IMAGE_PIX_TYPE_RGB888_QINT16),
    DL_IMAGE_PIX_CVT_RGB565LE2BGR888 = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565LE, DL_IMAGE_PIX_TYPE_BGR888),
    DL_IMAGE_PIX_CVT_RGB565LE2BGR888_QINT8 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565LE, DL_IMAGE_PIX_TYPE_BGR888_QINT8),
    DL_IMAGE_PIX_CVT_RGB565LE2BGR888_QINT16 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565LE, DL_IMAGE_PIX_TYPE_BGR888_QINT16),
    DL_IMAGE_PIX_CVT_RGB565LE2GRAY = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565LE, DL_IMAGE_PIX_TYPE_GRAY),
    DL_IMAGE_PIX_CVT_RGB565LE2GRAY_QINT8 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565LE, DL_IMAGE_PIX_TYPE_GRAY_QINT8),
    DL_IMAGE_PIX_CVT_RGB565LE2GRAY_QINT16 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565LE, DL_IMAGE_PIX_TYPE_GRAY_QINT16),
    DL_IMAGE_PIX_CVT_RGB565LE2RGB565LE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565LE, DL_IMAGE_PIX_TYPE_RGB565LE),
    DL_IMAGE_PIX_CVT_RGB565LE2RGB565BE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565LE, DL_IMAGE_PIX_TYPE_RGB565BE),
    DL_IMAGE_PIX_CVT_RGB565LE2BGR565LE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565LE, DL_IMAGE_PIX_TYPE_BGR565LE),
    DL_IMAGE_PIX_CVT_RGB565LE2BGR565BE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565LE, DL_IMAGE_PIX_TYPE_BGR565BE),
    DL_IMAGE_PIX_CVT_RGB565LE2HSV = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565LE, DL_IMAGE_PIX_TYPE_HSV),
    DL_IMAGE_PIX_CVT_RGB565LE2HSV_MASK = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565LE, DL_IMAGE_PIX_TYPE_HSV_MASK),
    DL_IMAGE_PIX_CVT_RGB565BE2RGB888 = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565BE, DL_IMAGE_PIX_TYPE_RGB888),
    DL_IMAGE_PIX_CVT_RGB565BE2RGB888_QINT8 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565BE, DL_IMAGE_PIX_TYPE_RGB888_QINT8),
    DL_IMAGE_PIX_CVT_RGB565BE2RGB888_QINT16 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565BE, DL_IMAGE_PIX_TYPE_RGB888_QINT16),
    DL_IMAGE_PIX_CVT_RGB565BE2BGR888 = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565BE, DL_IMAGE_PIX_TYPE_BGR888),
    DL_IMAGE_PIX_CVT_RGB565BE2BGR888_QINT8 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565BE, DL_IMAGE_PIX_TYPE_BGR888_QINT8),
    DL_IMAGE_PIX_CVT_RGB565BE2BGR888_QINT16 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565BE, DL_IMAGE_PIX_TYPE_BGR888_QINT16),
    DL_IMAGE_PIX_CVT_RGB565BE2GRAY = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565BE, DL_IMAGE_PIX_TYPE_GRAY),
    DL_IMAGE_PIX_CVT_RGB565BE2GRAY_QINT8 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565BE, DL_IMAGE_PIX_TYPE_GRAY_QINT8),
    DL_IMAGE_PIX_CVT_RGB565BE2GRAY_QINT16 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565BE, DL_IMAGE_PIX_TYPE_GRAY_QINT16),
    DL_IMAGE_PIX_CVT_RGB565BE2RGB565LE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565BE, DL_IMAGE_PIX_TYPE_RGB565LE),
    DL_IMAGE_PIX_CVT_RGB565BE2RGB565BE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565BE, DL_IMAGE_PIX_TYPE_RGB565BE),
    DL_IMAGE_PIX_CVT_RGB565BE2BGR565LE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565BE, DL_IMAGE_PIX_TYPE_BGR565LE),
    DL_IMAGE_PIX_CVT_RGB565BE2BGR565BE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565BE, DL_IMAGE_PIX_TYPE_BGR565BE),
    DL_IMAGE_PIX_CVT_RGB565BE2HSV = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565BE, DL_IMAGE_PIX_TYPE_HSV),
    DL_IMAGE_PIX_CVT_RGB565BE2HSV_MASK = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_RGB565BE, DL_IMAGE_PIX_TYPE_HSV_MASK),
    DL_IMAGE_PIX_CVT_BGR565LE2RGB888 = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565LE, DL_IMAGE_PIX_TYPE_RGB888),
    DL_IMAGE_PIX_CVT_BGR565LE2RGB888_QINT8 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565LE, DL_IMAGE_PIX_TYPE_RGB888_QINT8),
    DL_IMAGE_PIX_CVT_BGR565LE2RGB888_QINT16 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565LE, DL_IMAGE_PIX_TYPE_RGB888_QINT16),
    DL_IMAGE_PIX_CVT_BGR565LE2BGR888 = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565LE, DL_IMAGE_PIX_TYPE_BGR888),
    DL_IMAGE_PIX_CVT_BGR565LE2BGR888_QINT8 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565LE, DL_IMAGE_PIX_TYPE_BGR888_QINT8),
    DL_IMAGE_PIX_CVT_BGR565LE2BGR888_QINT16 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565LE, DL_IMAGE_PIX_TYPE_BGR888_QINT16),
    DL_IMAGE_PIX_CVT_BGR565LE2GRAY = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565LE, DL_IMAGE_PIX_TYPE_GRAY),
    DL_IMAGE_PIX_CVT_BGR565LE2GRAY_QINT8 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565LE, DL_IMAGE_PIX_TYPE_GRAY_QINT8),
    DL_IMAGE_PIX_CVT_BGR565LE2GRAY_QINT16 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565LE, DL_IMAGE_PIX_TYPE_GRAY_QINT16),
    DL_IMAGE_PIX_CVT_BGR565LE2RGB565LE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565LE, DL_IMAGE_PIX_TYPE_RGB565LE),
    DL_IMAGE_PIX_CVT_BGR565LE2RGB565BE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565LE, DL_IMAGE_PIX_TYPE_RGB565BE),
    DL_IMAGE_PIX_CVT_BGR565LE2BGR565LE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565LE, DL_IMAGE_PIX_TYPE_BGR565LE),
    DL_IMAGE_PIX_CVT_BGR565LE2BGR565BE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565LE, DL_IMAGE_PIX_TYPE_BGR565BE),
    DL_IMAGE_PIX_CVT_BGR565LE2HSV = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565LE, DL_IMAGE_PIX_TYPE_HSV),
    DL_IMAGE_PIX_CVT_BGR565LE2HSV_MASK = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565LE, DL_IMAGE_PIX_TYPE_HSV_MASK),
    DL_IMAGE_PIX_CVT_BGR565BE2RGB888 = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565BE, DL_IMAGE_PIX_TYPE_RGB888),
    DL_IMAGE_PIX_CVT_BGR565BE2RGB888_QINT8 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565BE, DL_IMAGE_PIX_TYPE_RGB888_QINT8),
    DL_IMAGE_PIX_CVT_BGR565BE2RGB888_QINT16 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565BE, DL_IMAGE_PIX_TYPE_RGB888_QINT16),
    DL_IMAGE_PIX_CVT_BGR565BE2BGR888 = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565BE, DL_IMAGE_PIX_TYPE_BGR888),
    DL_IMAGE_PIX_CVT_BGR565BE2BGR888_QINT8 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565BE, DL_IMAGE_PIX_TYPE_BGR888_QINT8),
    DL_IMAGE_PIX_CVT_BGR565BE2BGR888_QINT16 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565BE, DL_IMAGE_PIX_TYPE_BGR888_QINT16),
    DL_IMAGE_PIX_CVT_BGR565BE2GRAY = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565BE, DL_IMAGE_PIX_TYPE_GRAY),
    DL_IMAGE_PIX_CVT_BGR565BE2GRAY_QINT8 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565BE, DL_IMAGE_PIX_TYPE_GRAY_QINT8),
    DL_IMAGE_PIX_CVT_BGR565BE2GRAY_QINT16 =
        DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565BE, DL_IMAGE_PIX_TYPE_GRAY_QINT16),
    DL_IMAGE_PIX_CVT_BGR565BE2RGB565LE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565BE, DL_IMAGE_PIX_TYPE_RGB565LE),
    DL_IMAGE_PIX_CVT_BGR565BE2RGB565BE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565BE, DL_IMAGE_PIX_TYPE_RGB565BE),
    DL_IMAGE_PIX_CVT_BGR565BE2BGR565LE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565BE, DL_IMAGE_PIX_TYPE_BGR565LE),
    DL_IMAGE_PIX_CVT_BGR565BE2BGR565BE = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565BE, DL_IMAGE_PIX_TYPE_BGR565BE),
    DL_IMAGE_PIX_CVT_BGR565BE2HSV = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565BE, DL_IMAGE_PIX_TYPE_HSV),
    DL_IMAGE_PIX_CVT_BGR565BE2HSV_MASK = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_BGR565BE, DL_IMAGE_PIX_TYPE_HSV_MASK),
    DL_IMAGE_PIX_CVT_HSV2HSV_MASK = DL_IMAGE_PIX_CVT_ID(DL_IMAGE_PIX_TYPE_HSV, DL_IMAGE_PIX_TYPE_HSV_MASK)
} pix_cvt_t;

inline constexpr int align_up(int num, int align) noexcept
{
    return (num + align - 1) & ~(align - 1);
}

inline bool is_pix_type_quant(pix_type_t pix_type)
{
    switch (pix_type) {
    case DL_IMAGE_PIX_TYPE_RGB888_QINT8:
    case DL_IMAGE_PIX_TYPE_RGB888_QINT16:
    case DL_IMAGE_PIX_TYPE_BGR888_QINT8:
    case DL_IMAGE_PIX_TYPE_BGR888_QINT16:
    case DL_IMAGE_PIX_TYPE_GRAY_QINT8:
    case DL_IMAGE_PIX_TYPE_GRAY_QINT16:
        return true;
    default:
        return false;
    }
}

inline size_t get_pix_byte_size(pix_type_t pix_type)
{
    switch (pix_type) {
    case DL_IMAGE_PIX_TYPE_RGB888:
    case DL_IMAGE_PIX_TYPE_RGB888_QINT8:
    case DL_IMAGE_PIX_TYPE_BGR888:
    case DL_IMAGE_PIX_TYPE_BGR888_QINT8:
    case DL_IMAGE_PIX_TYPE_HSV:
        return 3;
    case DL_IMAGE_PIX_TYPE_RGB565LE:
    case DL_IMAGE_PIX_TYPE_RGB565BE:
    case DL_IMAGE_PIX_TYPE_BGR565LE:
    case DL_IMAGE_PIX_TYPE_BGR565BE:
    case DL_IMAGE_PIX_TYPE_GRAY_QINT16:
        return 2;
    case DL_IMAGE_PIX_TYPE_GRAY:
    case DL_IMAGE_PIX_TYPE_GRAY_QINT8:
    case DL_IMAGE_PIX_TYPE_HSV_MASK:
        return 1;
    case DL_IMAGE_PIX_TYPE_RGB888_QINT16:
    case DL_IMAGE_PIX_TYPE_BGR888_QINT16:
        return 6;
    default:
        return 0;
    }
}

inline int get_pix_channel_num(pix_type_t pix_type)
{
    switch (pix_type) {
    case DL_IMAGE_PIX_TYPE_RGB888:
    case DL_IMAGE_PIX_TYPE_RGB888_QINT8:
    case DL_IMAGE_PIX_TYPE_RGB888_QINT16:
    case DL_IMAGE_PIX_TYPE_BGR888:
    case DL_IMAGE_PIX_TYPE_BGR888_QINT8:
    case DL_IMAGE_PIX_TYPE_BGR888_QINT16:
    case DL_IMAGE_PIX_TYPE_RGB565LE:
    case DL_IMAGE_PIX_TYPE_RGB565BE:
    case DL_IMAGE_PIX_TYPE_BGR565LE:
    case DL_IMAGE_PIX_TYPE_BGR565BE:
    case DL_IMAGE_PIX_TYPE_HSV:
        return 3;
    case DL_IMAGE_PIX_TYPE_GRAY:
    case DL_IMAGE_PIX_TYPE_GRAY_QINT8:
    case DL_IMAGE_PIX_TYPE_GRAY_QINT16:
    case DL_IMAGE_PIX_TYPE_HSV_MASK:
        return 1;
    default:
        return -1;
    }
}

typedef struct img_s {
    void *data;
    uint16_t width;
    uint16_t height;
    pix_type_t pix_type;

    int channel() const { return get_pix_channel_num(pix_type); }
    size_t bytes() const { return width * height * get_pix_byte_size(pix_type); }
    bool pix_quant() const { return is_pix_type_quant(pix_type); }
    int col_step() const { return get_pix_byte_size(pix_type); }
    int row_step() const { return width * get_pix_byte_size(pix_type); }
} img_t;

typedef struct {
    void *data;
    size_t data_len;
} jpeg_img_t;

} // namespace image
} // namespace dl
