.build_template: &build_template
  stage: build
  tags:
    - build
  image: ${IMAGE}
  variables:
    # Enable ccache for all build jobs. See configure_ci_environment.sh for more ccache related settings.
    IDF_CCACHE_ENABLE: "1"
    BATCH_BUILD: "1"
    V: "0"
    WARNING_STR: ""

.build_ops_template: &build_ops_template
  <<: *build_template
  artifacts:
    when: always
    paths:
      - "**/build*/*.bin"
      # upload to s3 server to save the artifacts size
      - "**/build*/*.map"
      - "**/build*/*.elf"
      - "**/build*/flasher_args.json"
      - "**/build*/flash_project_args"
      - "**/build*/config/sdkconfig.json"
      - "**/build*/bootloader/*.bin"
      - "**/build*/bootloader/*.elf"
      - "**/build*/partition_table/*.bin"
      - "**/build*/espdl_models/*.espdl"
    expire_in: 1 week
  variables:
    IDF_CI_BUILD: "1"
      # By configuring this macro, you can append the compiled configuration file.
    # For example, using "sdkconf.etc=default" specifies the default sdkconfig file.
    EXAMPLE_CONFIG: "="
  script:
    - pip install --upgrade idf-component-manager
    - pip install idf_build_apps==2.4.3
    - python test_apps/build_apps.py ${EXAMPLE_DIR} -m ${MODEL_PATH} -t ${TARGET} -vv

.build_examples_template: &build_examples_template
  <<: *build_template
  artifacts:
    when: always
    paths:
      - "**/build*/*.bin"
      # upload to s3 server to save the artifacts size
      - "**/build*/*.map"
      - "**/build*/*.elf"
      - "**/build*/flasher_args.json"
      - "**/build*/flash_project_args"
      - "**/build*/config/sdkconfig.json"
      - "**/build*/bootloader/*.bin"
      - "**/build*/bootloader/*.elf"
      - "**/build*/partition_table/*.bin"
      - "**/build*/espdl_models/*.espdl"
    expire_in: 1 week
  variables:
    IDF_CI_BUILD: "1"
      # By configuring this macro, you can append the compiled configuration file.
    # For example, using "sdkconf.etc=default" specifies the default sdkconfig file.
    EXAMPLE_CONFIG: "="
  script:
    - pip install --upgrade idf-component-manager
    - pip install idf_build_apps==2.4.3
    - python test_apps/build_apps.py ${EXAMPLE_DIR} -t ${TARGET} -vv

build_espdl_ops:
  extends:
    - .build_ops_template
    - .rules:build:espdl_ops
  parallel:
    matrix:
      - IMAGE: [espressif/idf:release-v5.3, espressif/idf:latest]
        TARGET: [esp32p4, esp32s3]
  variables:
    EXAMPLE_DIR: test_apps/esp-dl
    MODEL_PATH: test_apps/esp-dl/models

build_example_human_face_recognition:
  extends:
    - .build_examples_template
    - .rules:build:example_human_face_recognition
  parallel:
    matrix:
      - IMAGE: [espressif/idf:release-v5.3, espressif/idf:latest]
        TARGET: [esp32p4, esp32s3]
  variables:
    EXAMPLE_DIR: examples/human_face_recognition
  
build_example_human_face_detect:
  extends:
    - .build_examples_template
    - .rules:build:example_human_face_detect
  parallel:
    matrix:
      - IMAGE: [espressif/idf:release-v5.3, espressif/idf:latest]
        TARGET: [esp32p4, esp32s3]
  variables:
    EXAMPLE_DIR: examples/human_face_detect

build_example_pedestrian_detect:
  extends:
    - .build_examples_template
    - .rules:build:example_pedestrian_detect
  parallel:
    matrix:
      - IMAGE: [espressif/idf:release-v5.3, espressif/idf:latest]
        TARGET: [esp32p4, esp32s3]
  variables:
    EXAMPLE_DIR: examples/pedestrian_detect


build_example_mobilenet_v2:
  extends:
    - .build_examples_template
    - .rules:build:example_mobilenet_v2
  parallel:
    matrix:
      - IMAGE: [espressif/idf:release-v5.3, espressif/idf:latest]
        TARGET: [esp32p4, esp32s3]
  variables:
    EXAMPLE_DIR: examples/mobilenet_v2

.build_docs_template:
  stage: build
  image: "$CI_DOCKER_REGISTRY/esp-idf-doc-env-v5.3:1-1"

build_esp_dl_html:
  extends:
    - .build_docs_template
  variables:
    DOCS_DIR: $CI_PROJECT_DIR/docs
  artifacts:
    when: always
    paths:
      - $DOCS_DIR/_build/*/*/html/*
      - $DOCS_DIR/_build/*/*/*.txt
    expire_in: 4 days
  script:
    - cd $DOCS_DIR
    - bash ./check_lang_folder_sync.sh
    - pip install -r requirements.txt
    - build-docs --skip-reqs-check -l $DOCLANG
    - echo "ESP-DL documentation preview available at $CI_JOB_URL/artifacts/file/docs/_build/$DOCLANG/$DOCTGT/html/index.html"
  parallel:
    matrix:
      - DOCLANG: ["en", "zh_CN"]

build_esp_dl_pdf:
  extends:
    - .build_docs_template
  variables:
    DOCS_DIR: $CI_PROJECT_DIR/docs
  artifacts:
    when: always
    paths:
      - $DOCS_DIR/_build/*/*/latex/*
      - $DOCS_DIR/_build/*/*/*.txt
    expire_in: 4 days
  script:
    - cd $DOCS_DIR
    - bash ./check_lang_folder_sync.sh
    - pip install -r requirements.txt
    - build-docs --skip-reqs-check -bs latex -l $DOCLANG
  parallel:
    matrix:
      - DOCLANG: ["en", "zh_CN"]
